# Generated by Django 2.1.7 on 2019-06-30 06:34

import datetime
from django.db import migrations, models
import markdownx.models
import myblog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tag_line', models.CharField(default='', max_length=300, null=True)),
                ('header_image', models.ImageField(null=True, upload_to=myblog.models.category_header_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('message', models.TextField(max_length=1000)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150)),
                ('subtitle', models.CharField(default='', max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('body', markdownx.models.MarkdownxField()),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('date_published', models.DateField(default=datetime.date.today)),
                ('is_published', models.BooleanField(default=False)),
                ('header_image', models.ImageField(null=True, upload_to=myblog.models.post_header_image_path)),
                ('categories', models.ManyToManyField(to='myblog.Category')),
            ],
        ),
    ]
